api = "0.2"

[buildpack]
id = "google.go.appengine"
version = "0.9.0"
name = "Go - App Engine"

[[stacks]]
id = "google.go111"

[[stacks]]
id = "google.go112"

[[stacks]]
id = "google.go113"

[[stacks]]
id = "google.go116"

[[stacks]]
id = "google.go114"

[[stacks]]
id = "google.go115"

[[stacks]]
id = "google.go116"
