api = "0.2"

[buildpack]
id = "google.python.appengine"
version = "0.9.0"
name = "Python - App Engine"

[[stacks]]
id = "google.python37"

[[stacks]]
id = "google.python38"

[[stacks]]
id = "google.python39"
