description = "Builder for the GAE Ruby 2.5 runtime"

[[buildpacks]]
  id = "google.ruby.appengine_validation"
  uri = "appengine_validation.tgz"

[[buildpacks]]
  id = "google.ruby.appengine"
  uri = "appengine.tgz"

[[buildpacks]]
  id = "google.ruby.bundle"
  uri = "bundle.tgz"

[[buildpacks]]
  id = "google.ruby.rails"
  uri = "rails.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]
  [[order.group]]
    id = "google.ruby.appengine_validation"
    optional = true

  [[order.group]]
    id = "google.ruby.bundle"

  [[order.group]]
    id = "google.ruby.rails"
    optional = true

  [[order.group]]
    id = "google.ruby.appengine"

  [[order.group]]
    id = "google.utils.label"

[stack]
  id = "google.ruby25"
  build-image = "gcr.io/gae-runtimes/buildpacks/ruby25/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/ruby25/run"

[lifecycle]
  version = "0.11.1"
